##############################################################
##############################################################
# This is an example configuration provided by Wraith.
# Feel free to amend for your own requirements.
# ---
# This particular config is intended to demonstrate how
# to use Wraith in 'capture' mode, which is best suited to
# comparing a test and live version of the same website.
#
# `wraith capture capture.yaml`
#
##############################################################
##############################################################

# (required) The engine to run Wraith with. Examples: 'phantomjs', 'casperjs', 'slimerjs'
browser: "phantomjs"

# (required) The directory that your screenshots will be stored in
directory: 'reports/cgudev_top50'


# (required) The domains to take screenshots of.
domains:
  kentico:  "http://syd-lb.cgu.com.au.wwwserver.com.au"
  drupaldev:      "http://dev.cgu.iagdev.net"

# (required) The paths to capture. All paths should exist for both of the domains specified above.
paths:
  "personal": "/personal"
  "business": "/business"
  "personal_find_an_insurance_adviser": "/personal/find-an-insurance-adviser"
  "business_workers_compensation": "/business/workers-compensation"
  "business_products_trades_cover": "/business/products/trades-cover"
  "personal_products_car_insurance": "/personal/products/car-insurance"
  "business_products_public_liability_insurance": "/business/products/public-liability-insurance"
  "contact": "/contact"
  "personal_products_home_insurance": "/personal/products/home-insurance"
  "personal_contact": "/personal/contact"
  "business_products_professional_indemnity_insurance": "/business/products/professional-indemnity-insurance"
  "personal_products_car_insurance_comprehensive_car_insurance": "/personal/products/car-insurance/comprehensive-car-insurance"
  "personal_claims": "/personal/claims"
  "personal_products_manage_policy": "/personal/products/manage-policy"
  "business_find_an_insurance_adviser": "/business/find-an-insurance-adviser"
  "search_searchtext": "/search?searchtext=x"
  "about_cgu": "/about-cgu"
  "contact_update_policy_details": "/contact/update-policy-details"
  "business_products_professionals_cover": "/business/products/professionals-cover"
  "business_explore_business_understanding_liability_and_indemnity": "/business/explore-business/understanding-liability-and-indemnity"
  "business_products_business_pack": "/business/products/business-pack"
  "personal_products_travel_insurance": "/personal/products/travel-insurance"
  "business_workers_compensation_vic_for_employers": "/business/workers-compensation/vic/for-employers"
  "business_products_commercial_motor": "/business/products/commercial-motor"
  "personal_products": "/personal/products"
  "personal_claims_making_a_claim": "/personal/claims/making-a-claim"
  "personal_products_landlords_insurance": "/personal/products/landlords-insurance"
  "business_claims_making_a_claim": "/business/claims/making-a-claim"
  "community_coach": "/community-coach"
  "for_advisers": "/for-advisers"
  "contact_request_certificate_of_currency": "/contact/request-certificate-of-currency-(1)"
  "business_products_workers_compensation": "/business/products/workers-compensation"
  "business_products": "/business/products"
  "business_products_manage_policy": "/business/products/manage-policy"
  "personal_products_home_insurance_accidental_damage_home_insurance": "/personal/products/home-insurance/accidental-damage-home-insurance"
  "personal_products_caravan_insurance": "/personal/products/caravan-insurance"
  "personal_products_residential_strata_insurance": "/personal/products/residential-strata-insurance"
  "error_aspx": "/error.aspx"
  "afltipping_thankyou": "/afltipping-thankyou"
  "personal_learn_about_insurance_calculators": "/personal/learn-about-insurance/calculators"
  "contact_general_enquiry": "/contact/general-enquiry"
  "personal_products_home_insurance_compare_home_insurance": "/personal/products/home-insurance/compare-home-insurance"
  "business_workers_compensation_vic": "/business/workers-compensation/vic"
  "business_products_farm_pack": "/business/products/farm-pack"
  "personal_products_home_insurance_home_contents_transit_insurance": "/personal/products/home-insurance/home-contents-transit-insurance"
  "system_wc_resources_for_employers_tools_and_resources_for_employers_forms_downloads_for_employers": "/system/wc-resources/for-employers/tools-and-resources-for-employers/forms-downloads-for-employers"
  "contact_update_policy_details.aspx": "/contact/update-policy-details.aspx"
  "personal_claims_claims_faq": "/personal/claims/claims-faq"
  "business_workers_compensation_wa_for_employers": "/business/workers-compensation/wa/for-employers"
  "about_cgu_careers": "/about-cgu/careers"  

# (required) Screen widths (and optional height) to resize the browser to before taking the screenshot.
screen_widths:
  - 320x1500
#  - 600x768
#  - 768
#  - 1024
  - 1280x2000

# (optional) JavaScript file to execute before taking screenshot of every path. Default: nil
# before_capture: 'javascript/disable_javascript--phantom.js'
# before_capture: 'javascript/cgu-cleanup.js'

# (required) Amount of fuzz ImageMagick will use when comparing images. A higher fuzz makes the comparison less strict.
fuzz: '20%'

# (optional) The maximum acceptable level of difference (in %) between two images before Wraith reports a failure. Default: 0
threshold: 5

# (optional) Specify the template (and generated thumbnail sizes) for the gallery output.
gallery:
  template: 'basic_template' # Examples: 'basic_template' (default), 'slideshow_template'
  thumb_width:  200
  thumb_height: 200

# (optional) Choose which results are displayed in the gallery, and in what order. Default: alphanumeric
# Options:
#   alphanumeric - all paths (with or without a difference) are shown, sorted by path
#   diffs_first - all paths (with or without a difference) are shown, sorted by difference size (largest first)
#   diffs_only - only paths with a difference are shown, sorted by difference size (largest first)
# Note: different screen widths are always grouped together.
mode: diffs_first
