##############################################################
##############################################################
# This is an example configuration provided by Wraith.
# Feel free to amend for your own requirements.
# ---
# This particular config is intended to demonstrate how
# to use Wraith in 'capture' mode, which is best suited to
# comparing a test and live version of the same website.
#
# `wraith capture capture.yaml`
#
##############################################################
##############################################################

# (required) The engine to run Wraith with. Examples: 'phantomjs', 'casperjs', 'slimerjs'
browser: "phantomjs"

# (required) The domains to take screenshots of.
domains:
  kentico:  "http://syd-lb.cgu.com.au.wwwserver.com.au"
  drupaldev:      "http://dev.cgu.iagdev.net"
  #drupaldev:      "http://dev.cgu.iagdev.net"

# (required) The directory that your screenshots will be stored in
directory: 'reports/cgudev_aboutus'

# (required) The paths to capture. All paths should exist for both of the domains specified above.
paths:
  "about_cgu": "/About-CGU"
  "about_cgu_Careers": "/About-CGU/Careers"
  "about_cgu_Careers_career_development": "/About-CGU/Careers/career-development"
  "about_cgu_Careers_community_engagement": "/About-CGU/Careers/community-engagement"
  "about_cgu_Careers_culture_and_values": "/About-CGU/Careers/culture-and-values"
  "about_cgu_Careers_Join_CGU": "/About-CGU/Careers/Join-CGU"
  "about_cgu_Careers_our_business_areas": "/About-CGU/Careers/our-business-areas"
  "about_cgu_Careers_reward": "/About-CGU/Careers/reward"
  "about_cgu_Who_we_are": "/About-CGU/Who-we-are"
  "about_cgu_Who_we_are_About_IAG": "/About-CGU/Who-we-are/About-IAG"
  "about_cgu_Who_we_are_Collingwood": "/About-CGU/Who-we-are/Collingwood.aspx"
  "about_cgu_Who_we_are_community_engagement": "/About-CGU/Who-we-are/community-engagement"
  "about_cgu_Who_we_are_customer_commitment": "/About-CGU/Who-we-are/customer-commitment"
  "about_cgu_Who_we_are_Meet_David": "/About-CGU/Who-we-are/Meet-David"
  "about_cgu_Who_we_are_our_leadership": "/About-CGU/Who-we-are/our-leadership"
  "about_cgu_Who_we_are_our_partners": "/About-CGU/Who-we-are/our-partners"
  "about_cgu_Who_we_are_our_sponsorships": "/About-CGU/Who-we-are/our-sponsorships"
  "about_cgu_Who_we_are_Our_Vision": "/About-CGU/Who-we-are/Our-Vision"
  "about_cgu_Who_we_are_meet_brendon": "/About-CGU/Who-we-are/meet-brendon"
  "about_cgu_Who_we_are_meet_max": "/About-CGU/Who-we-are/meet-max.aspx"
  "about_cgu_Who_we_are_our_awards": "/About-CGU/Who-we-are/our-awards"
  "about_cgu_Who_we_are_our_partners_smea": "/About-CGU/Who-we-are/our-partners/smea"
  "about_cgu_Who_we_are_our_partners_xero": "/About-CGU/Who-we-are/our-partners/xero"
  "about_cgu_Who_we_are_shareholders": "/About-CGU/Who-we-are/shareholders"
  "diversity": "/About-CGU/Careers/diversity,-inclusion-and-flexibility"
  # "about_cgu_Who_we_are_Collingwood_Jay_s_story": "/About-CGU/Who-we-are/Collingwood/Jay-s-story" #special
  # "about_cgu_Who_we_are_Collingwood_Levi_s_story": "/About-CGU/Who-we-are/Collingwood/Levi-s-story" #special
  # "about_cgu_Who_we_are_Collingwood_Mason_s_story": "/About-CGU/Who-we-are/Collingwood/Mason-s-story" #special
  # "about_cgu_Who_we_are_Collingwood_Nathans_story": "/About-CGU/Who-we-are/Collingwood/Nathan%E2%80%99s-story" #special
  # "about_cgu_Who_we_are_Community_Engagement": "/About-CGU/Who-we-are/Community-Engagement"
  # "about_cgu_Who_we_are_Meet_David_meet_leo_video": "/About-CGU/Who-we-are/Meet-David/meet-leo-video"
  # "about_cgu_Who_we_are_meet_max_episode_1_hire_the_right_people": "/About-CGU/Who-we-are/meet-max/episode-1-hire-the-right-people"
  # "about_cgu_Who_we_are_meet_max_episode_2_do_your_homework": "/About-CGU/Who-we-are/meet-max/episode-2-do-your-homework"
  # "about_cgu_Who_we_are_meet_max_episode_3_business_before_pleasure": "/About-CGU/Who-we-are/meet-max/episode-3-business-before-pleasure"
  # "about_cgu_Who_we_are_meet_max_episode_4_the_rewards_aren_t_just_financial": "/About-CGU/Who-we-are/meet-max/episode-4-the-rewards-aren-t-just-financial"
  # "about_cgu_Who_we_are_our_partners_bankvic": "/About-CGU/Who-we-are/our-partners/bankvic"
  # "about_cgu_Who_we_are_our_partners_bendigo_bank": "/About-CGU/Who-we-are/our-partners/bendigo-bank"
  # "about_cgu_Who_we_are_our_partners_bupa": "/About-CGU/Who-we-are/our-partners/bupa"
  # "about_cgu_Who_we_are_our_partners_defence_bank": "/About-CGU/Who-we-are/our-partners/defence-bank"
  # "about_cgu_Who_we_are_our_partners_hbf": "/About-CGU/Who-we-are/our-partners/hbf"
  # "about_cgu_Who_we_are_our_partners_mystate": "/About-CGU/Who-we-are/our-partners/mystate"
  # "about_cgu_Who_we_are_our_partners_peoples_choice_credit_union": "/About-CGU/Who-we-are/our-partners/peoples-choice-credit-union"
  # "about_cgu_Who_we_are_our_partners_qtmb": "/About-CGU/Who-we-are/our-partners/qtmb"
  # "about_cgu_Who_we_are_our_partners_queensland_country_credit_union": "/About-CGU/Who-we-are/our-partners/queensland-country-credit-union"
  # "about_cgu_Who_we_are_our_partners_victoria_teachers_mutual_bank": "/About-CGU/Who-we-are/our-partners/victoria-teachers-mutual-bank"
  # "about_cgu_contact": "/About-CGU/contact"

# (required) Screen widths (and optional height) to resize the browser to before taking the screenshot.
screen_widths:
  - 320x1500
#  - 600x768
#  - 768
#  - 1024
  - 1280x2000

# (optional) JavaScript file to execute before taking screenshot of every path. Default: nil
# before_capture: 'javascript/disable_javascript--phantom.js'
# before_capture: 'javascript/cgu-cleanup.js'

# (required) Amount of fuzz ImageMagick will use when comparing images. A higher fuzz makes the comparison less strict.
fuzz: '20%'

# (optional) The maximum acceptable level of difference (in %) between two images before Wraith reports a failure. Default: 0
threshold: 5

# (optional) Specify the template (and generated thumbnail sizes) for the gallery output.
gallery:
  template: 'basic_template' # Examples: 'basic_template' (default), 'slideshow_template'
  thumb_width:  400
  thumb_height: 400

# (optional) Choose which results are displayed in the gallery, and in what order. Default: alphanumeric
# Options:
#   alphanumeric - all paths (with or without a difference) are shown, sorted by path
#   diffs_first - all paths (with or without a difference) are shown, sorted by difference size (largest first)
#   diffs_only - only paths with a difference are shown, sorted by difference size (largest first)
# Note: different screen widths are always grouped together.
mode: diffs_first
