##############################################################
##############################################################
# This is an example configuration provided by Wraith.
# Feel free to amend for your own requirements.
# ---
# This particular config is intended to demonstrate how
# to use Wraith in 'capture' mode, which is best suited to
# comparing a test and live version of the same website.
#
# `wraith capture capture.yaml`
#
##############################################################
##############################################################

# (required) The engine to run Wraith with. Examples: 'phantomjs', 'casperjs', 'slimerjs'
browser: "phantomjs"

# (required) The directory that your screenshots will be stored in
directory: 'reports/cgudev_business'


# (required) The domains to take screenshots of.
domains:
  kentico:  "http://syd-lb.cgu.com.au.wwwserver.com.au"
  drupaldev:      "http://dev.cgu.iagdev.net"

# (required) The paths to capture. All paths should exist for both of the domains specified above.
paths:
  "business": "/business"
  "products_trades-cover": "/business/products/trades-cover"
  "workers-compensation": "/business/workers-compensation"
  "products_professional-indemnity-insurance": "/business/products/professional-indemnity-insurance"
  "products_public-liability-insurance": "/business/products/public-liability-insurance"
  "explore-business_understanding-liability-and-indemnity": "/business/explore-business/understanding-liability-and-indemnity"
  "products_professionals-cover": "/business/products/professionals-cover"
  "workers-compensation_vic_for-employers": "/business/workers-compensation/vic/for-employers"
  "products_commercial-motor": "/business/products/commercial-motor"
  "products_business-pack": "/business/products/business-pack"
  "claims_making-a-claim": "/business/claims/making-a-claim"
  "products_manage-policy": "/business/products/manage-policy"
  "products": "/business/products"
  "workers-compensation_vic": "/business/workers-compensation/vic"
  "workers-compensation_wa_for-employers": "/business/workers-compensation/wa/for-employers"
  "products_professional-indemnity": "/business/products/professional-indemnity"
  "workers-compensation_nsw_for-employers_tools-and-resources-for-employers_forms-downloads-for-employers": "/business/workers-compensation/nsw/for-employers/tools-and-resources-for-employers/forms-downloads-for-employers"
  "products_workers-compensation": "/business/products/workers-compensation"
  "products_public-liability_professional-indemnity-broadform-liability": "/business/products/public-liability/professional-indemnity-broadform-liability"
  "contact": "/business/contact"
  "claims_claims-forms": "/business/claims/claims-forms"
  "claims": "/business/claims"
  "products_income-protection": "/business/products/income-protection"
  "workers-compensation_vic_for-injured-workers_contact-workers-compensation": "/business/workers-compensation/vic/for-injured-workers/contact-workers-compensation"
  "find-an-insurance-adviser": "/business/find-an-insurance-adviser"
  "workers-compensation_nsw": "/business/workers-compensation/nsw"
  "products_farm-pack": "/business/products/farm-pack"
  "products_commercial-property": "/business/products/commercial-property"
  "workers-compensation_nsw_for-injured-workers_contact-workers-compensation": "/business/workers-compensation/nsw/for-injured-workers/contact-workers-compensation"
  "products_public-liability-insurance_market-stall-insurance": "/business/products/public-liability-insurance/market-stall-insurance"
  "workers-compensation_vic_for-employers_tools-and-resources_forms-downloads-for-employers": "/business/workers-compensation/vic/for-employers/tools-and-resources/forms-downloads-for-employers"
  "workers-compensation_wa": "/business/workers-compensation/wa"
  "products_construction": "/business/products/construction"
  "workers-compensation_nsw_for-injured-workers": "/business/workers-compensation/nsw/for-injured-workers"
  "workers-compensation_vic_for-injured-workers": "/business/workers-compensation/vic/for-injured-workers"
  "products_it-professionals-cover": "/business/products/it-professionals-cover"
  "products_marine-cargo-commercial-hull_marine-cargo-commercial": "/business/products/marine-(cargo-commercial-hull)/marine-(cargo-commercial)"
  "workers-compensation_act_for-employers": "/business/workers-compensation/act/for-employers"
  "products_public-liability-insurance_professional-indemnity-broadform-liability": "/business/products/public-liability-insurance/professional-indemnity-broadform-liability"
  "products_machinery": "/business/products/machinery"
  "workers-compensation_tas_for-employers": "/business/workers-compensation/tas/for-employers"
  "workers-compensation_wa_for-employers_tools-and-resources-for-employers_forms-downloads-for-employers": "/business/workers-compensation/wa/for-employers/tools-and-resources-for-employers/forms-downloads-for-employers"
  "products_professional-indemnity-insurance_medical-indemnity": "/business/products/professional-indemnity-insurance/medical-indemnity"
  "products_public-liability_it-liability": "/business/products/public-liability/it-liability"
  "products_management-liability_business-protection-management-liability": "/business/products/management-liability/business-protection-management-liability"
  "products_directors-officers-liability": "/business/products/directors-officers-liability"
  "workers-compensation_nsw_for-employers_claims-for-employers_reporting-an-injury": "/business/workers-compensation/nsw/for-employers/claims-for-employers/reporting-an-injury"
  "products_farm-rural": "/business/products/farm-rural"
  "products_farm-rural_farm-motor-insurance": "/business/products/farm-rural/farm-motor-insurance"
  "workers-compensation_wa_for-employers_claims-for-employers_reporting-an-injury": "/business/workers-compensation/wa/for-employers/claims-for-employers/reporting-an-injury"
  "products_management-liability": "/business/products/management-liability"
  "claims_workers-compensation-claims": "/business/claims/workers-compensation-claims"
  "workers-compensation_vic_for-injured-workers_claims-information-for-injured-workers": "/business/workers-compensation/vic/for-injured-workers/claims-information-for-injured-workers"

# (required) Screen widths (and optional height) to resize the browser to before taking the screenshot.
screen_widths:
  - 320x1500
#  - 600x768
#  - 768
#  - 1024
  - 1280x2000

# (optional) JavaScript file to execute before taking screenshot of every path. Default: nil
# before_capture: 'javascript/disable_javascript--phantom.js'
# before_capture: 'javascript/cgu-cleanup.js'

# (required) Amount of fuzz ImageMagick will use when comparing images. A higher fuzz makes the comparison less strict.
fuzz: '20%'

# (optional) The maximum acceptable level of difference (in %) between two images before Wraith reports a failure. Default: 0
threshold: 5

# (optional) Specify the template (and generated thumbnail sizes) for the gallery output.
gallery:
  template: 'basic_template' # Examples: 'basic_template' (default), 'slideshow_template'
  thumb_width:  200
  thumb_height: 200

# (optional) Choose which results are displayed in the gallery, and in what order. Default: alphanumeric
# Options:
#   alphanumeric - all paths (with or without a difference) are shown, sorted by path
#   diffs_first - all paths (with or without a difference) are shown, sorted by difference size (largest first)
#   diffs_only - only paths with a difference are shown, sorted by difference size (largest first)
# Note: different screen widths are always grouped together.
mode: diffs_first
